name: Reporting unit test coverage
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]    
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Generate coverage report
      run: |
        npm ci
        npm test -- --coverage --watchAll=false
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        directory: ./coverage/
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        files: ./clover.xml
        flags: unittests
        name: codecov-umbrella
        path_to_write_report: ./coverage/codecov_report.txt
        verbose: true